# Generated by Django 4.2.16 on 2026-04-18 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('chef_projet', 'Chef de Projet'), ('chef_chantier', 'Chef de Chantier'), ('chef_equipe', "Chef d'Équipe"), ('pointeur', 'Pointeur')], default='pointeur', max_length=20)),
                ('fcm_token', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('lieu', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='planifie', max_length=20)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chef_chantier', models.ForeignKey(blank=True, limit_choices_to={'role': 'chef_chantier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers_en_tant_que_chef_chantier', to=settings.AUTH_USER_MODEL)),
                ('chef_projet', models.ForeignKey(blank=True, limit_choices_to={'role': 'chef_projet'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers_en_tant_que_chef_projet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chantier',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Terminée')], default='a_faire', max_length=20)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('urgente', 'Urgente 🔴')], default='moyenne', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='api.chantier')),
                ('chef_equipe', models.ForeignKey(blank=True, limit_choices_to={'role': 'chef_equipe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_assignees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche',
                'ordering': ['priorite', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='api.chantier')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Ouvrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('fonction', models.CharField(choices=[('macon', 'Maçon'), ('electricien', 'Électricien'), ('plombier', 'Plombier'), ('charpentier', 'Charpentier'), ('peintre', 'Peintre'), ('ferrailleur', 'Ferrailleur'), ('autre', 'Autre')], default='macon', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('date_arrivee', models.DateField(auto_now_add=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvriers', to='api.chantier')),
                ('pointeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvriers_ajoutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ouvrier',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='api.chantier')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
