# Generated by Django 4.2.16 on 2026-05-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rapport_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='factures/%Y/%m/', verbose_name='Document joint'),
        ),
    ]
