# Generated by Django 4.2.16 on 2026-05-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_facture_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='rapports/%Y/%m/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.rapport')),
            ],
        ),
    ]
